function Build-NuPkg([string] $nuspecFile)
{
    Write-Host -ForegroundColor Cyan "Building '$([IO.Path]::GetFileName($nuspecFile))'"

    [xml]$nuspec = Get-Content $nuspecFile
    $digits = $nuspec.package.metadata.version -split '\.'
    $digits[3] = $($($digits[3] -as [Int32]) + 1) -as [String]
    $version = $digits -join '.'

    .\New-NuGetPackage.ps1 -NuSpecFilePath "$nuspecFile" -VersionNumber $version -ReleaseNotes "Version $version" -NoPrompt
}

function Generate-SpecificationsFile()
{
    $file = '.\ttincludes\WCFAsyncQueryableServices.Specifications.Dependences.ttinclude'
    Write-Host -ForegroundColor Cyan  "Building '$file'"

    $list = New-Object "System.Collections.Generic.List``1[System.String]"
    foreach ($item in $(Get-Content '.\TestsDependences\TestsDependences\GetMembersVisitor.cs'))
    {
        $list.Add($item)
    }

    # remove using statements and namespace
    while ($list[0] -ne '{')
    {
        $list.RemoveAt(0);
    }
    $list.RemoveAt(0)
    $list.Reverse()
    while ($list[0] -ne '}')
    {
        $list.RemoveAt(0);
    }
    $list.RemoveAt(0)
    $list.Reverse()

    # strip leading spaces
    for ($i = 0; $i -lt $list.Count; $i++)
    {
        $line = $list[$i]
        if ($line.Length -gt 3 -and [String]::IsNullOrWhitespace($line.SubString(0, 4)))
        {
            $list[$i] = $line.SubString(4)
        }
    }

    # add new lines
    $list.Insert(0, '')
    $list.Insert(0, '// Generated by build script.')
    $list.Insert(0, '// Copyright (c) Matthieu MEZIL.  All rights reserved.')
    $list.Insert(0, '<#+')
    $list.Add('#>')

    # update the file
    $list | Set-Content $file
}

msbuild '.\NuGet Programs\WAQSNuGetPrograms.sln' /p:Platform=x86
if ($LASTEXITCODE)
{
    exit $LASTEXITCODE
}

msbuild '.\TestsDependences\TestsDependences.sln' /p:Platform="Any CPU"
if ($LASTEXITCODE)
{
    exit $LASTEXITCODE
}

vstest.console '.\TestsDependences\TestsDependences\bin\Debug\TestsDependences.dll'
if ($LASTEXITCODE)
{
    exit $LASTEXITCODE
}

Generate-SpecificationsFile

dir *.nuspec | % { Build-NuPkg($_.FullName) }
